### ISSUE TITLE
How to disable goose change color

### ISSUE THREAD

**Issue by gtf35** [LimitLost/GooseManager#2]
hello, when I enable mod, my goose is changing color all the time.
Do you have any good solution？

**Comment by nyakase** [comment]
This is not related to GooseManager. The Goose comes with a preinstalled "RainbowStrobe" mod, which is causing this issue.

**Comment by gtf35** [comment]
> This is not related to GooseManager. The Goose comes with a preinstalled "RainbowStrobe" mod, which is causing this issue.

got it，thanks
